### ISSUE TITLE
Password Length Problem

### ISSUE THREAD

**Issue by se** [vforteli/Flexinets.Radius.RadiusClient#2]
Hi @vforteli ,

If I send a password longer than 15 characters, I get an AccessReject error because probably the message is not transmitted properly.

Do you have any idea about this?

**Comment by se** [comment]
This is the debug window that I capture;

![image](https://user-images.githubusercontent.com/491844/39678923-aa32733a-519e-11e8-8a19-81d6d3e6e997.png)

**Comment by vforteli** [comment]
Hi, thats indeed a bug, and also one that Im definitely going to fix

**Comment by vforteli** [comment]
Fixed in vforteli/Flexinets.Radius.Core@afc3a20059652b621f45f589667cdf11ea5bdf97
Test added to vforteli/Flexinets.Radius.RadiusServer@645ee414a0d07b17afa5679608234f4f0e9500ef

**Comment by se** [comment]
@vforteli Can you update following packages versions too?

RadiusServer
RadiusClient

They are referencing the old version of the Core project.

Thank you.

**Comment by vforteli** [comment]
I will probably update them soon, but it shouldnt really matter that much. The references are not to specific versions  but >=1.3.0

**Comment by se** [comment]
I did it but nothing happened :-/ I will try it again and let you know.

**Comment by se** [comment]
It's OK now. Thank you.

**Comment by vforteli** [comment]
Did you reference the project or the nuget package?

**Comment by vforteli** [comment]
Ok great!
